---
title: "Split-Apply-Combine"
author: "Ashish Jain"
topic: "02"
layout: post
root: ../../../
---

##Split-Apply-Combine

1. **Which (base R) functions do you know that support the split-apply-combine strategy? In your opinion, are these sufficient - state why or why not?**.

In base R there are split, lapply, mapply, rbind, and cbind functions that support the split-apply-combine strategy. The split function is used to split the data; lapply, mapply, and tapply to apply a particular function to the data; rbind and cbind to combine the processed data on the basis of rows and columns respectively. In my opinion, these functions are not sufficient. These functions only take the input data in the form of matrixes and vectors. If the working data is of high dimensions, ragged, irregular, or incomplete then these methods will have problems. For these type of datasets, data frame is the right choice for storing the data. Due to these issues, many other packages has been developed including plyr, dplyr, and data.table which have effective and efficient split-combine-apply functions. 

2. **Using a dataset of your choice, describe how you can use the split-apply-combine strategy for a part of the data analysis.**

Now, we are going to work with a dataset on which we a

```{r}
library(rvest)
url <- "http://www.nytimes.com/elections/results/florida"
doc <- read_html(url)
tables <- html_table(doc, fill=TRUE)
head(tables[[2]])
```