---
title: "Split-Apply-Combine..."
author: "Kiegan Rice"
topic: "02"
layout: post
root: ../../../
---

## Which (base R) functions do you know that support the split-apply-combine strategy? In your opinion, are these sufficient - state why or why not?  

I don't believe that these functions are sufficient. While they allow us to do perform all the functions we need to, they aren't ideal in terms of computing time - for example, __for__ loops are much less efficient than even __apply__, as touched on in the article. I think that having a well streamlined and efficient set of functions in place - such as the __dplyr__ package that came after __plyr__ - is a much better option than using the functions I have listed above. It is also important to keep in mind that it is really easy for the split and apply part to get really messy with those base R functions. Code is hard to read and specific to a certain scenario, which doesn't make it easier to go back and change things if needed.

## Using a dataset of your choice, describe how you can use the split-apply-combine strategy for a part of the data analysis.  
What dataset should I use here?
