---
title: "Interactive Statistical Graphics"
author: "Firstname Lastname"
topic: "11"
layout: post
root: ../../../
---

## Background:

The ASA sections on Statistical Graphics and Statistical Computing are hosting a [video library](http://stat-graphics.org/movies/) of movies showcasing the 'state of the art' of the times. This library contains countless interesting insights into the history of computing and graphics. Watch J.W.Tukey demonstrate the  [Prim-9 system](http://stat-graphics.org/movies/prim9.html).

In the light of this video, write a blog post discussing the use of interactive graphics: how have you experienced interactive statistical graphics (and in which systems)? What operations do you consider to be part of interactive statistical graphics now? 

## Instructions:
Save a **copy** of this file, replacing "Lastname" and "Firstname" with your own and *leave the original unedited*.

In **your copy**, replace the `title:` and `author:` fields in the YAML above, while leaving the remaining fields intact. Remove the background and the instructions sections and write your blog post!

Once you are done, **create a pull request** to upload your changes to the original repository!

