---
title: "Licenses"
author: "Jo Papio"
topic: "09"
layout: post
root: ../../../
---

##Write a blog post discussing some of the pros (and cons) of the license you selected. 

I opted to read through the [MIT license](https://www.r-project.org/Licenses/MIT). I think at this point in my career, this is probably the safest choice, without any consultation of someone more familiar with the legalese, which I don't really have the experience to sort through and understand at a level I'd be comfortable with.

The most obvious pro of this option is that it's straight forward: *do whatever you want with this code, and I'm not responsible for anything that goes wrong*.

The most obvious con for this option is that if someone uses the work you've done in some sort of commercial application or for a profit, *I have relinquished any claim to credit for what goes right*. 

Discuss what would happen if a software company wants to use the package as part of their code and sell a product. What happens if the code doesn't work as expected and a user tries to sue you?
