---
title: "Software Licenses for R"
author: "Matt Stuart"
topic: "09"
layout: post
root: ../../../
---

I would likely choose a GNU General Public License Version 2.  The main benefit of this license is it gives the freedom for the creator to share and change the software for free, or charge for it if you so choose. You are also allowed to distribute other modifications or other work based on your previous code, send the original code as part of the program, and can add geographic restrictions based on the patent laws in other countries.  The biggest con of using this license is the fact that, because this is a free software, there is no warranty on the product, meaning if there is a defect in the program, the user is responsible for its quality control, which can prove very time consuming and expensive.

Under the licensing agreement section 4, any party wanting to use copies or rights of the program is able to do so as long as permission is given and both parties remain under full compliance.  Any other attempts will void any rights a user will have under this license.  Another option, under section 10, is that use for this program under another free software is available under permission from the author.  Even if a user tries to use the code and it fails to work, because the program is not under any warranty, any copyright holder is not liable for any damages the software may cause, even if the user is previously made aware of the possibility of such damages.
