---
title: "Literate Programming"
author: "Ashish Jain"
topic: "01"
layout: post
root: ../../../
---

## Background:
Based on the idea behind literate programming that Donald Knuth discusses in his talk, 
write a blog post on **how you have or could make use of literate programming in your work**.

Literate Programming, as the name suggests that it is an approach to write literature with the program. It is first introduced by Donald E. Knuth whose main intention is to make a person understand what is the logic behind a particular piece of code. The main motivation behind this is to explain things behind a particular program or a piece of code in simpler and interactive ways. In his talk, Donald E. Knuth talks about a number of examples in which literate programming has made reading programs very easy and interactive including books on MP3 format, TEX web program, and Complier design and implementation.

In his talk, Donald E. Knuth talks about the “paradox of open system”. He talks about this in the context of the various open source projects that are being running and how difficult it is to use or code for such projects due to lack of proper documentation and structure of the code. Each person working in an open source project has his own writing style and going through their code without any background is very difficult. I have frequently faced these issues while working on various tools in the field of Bioinformatics. 
 Many times, in his talk he talks about how literal programming can help in   One of the most important use of literal programming which has bee



- Examples of TEX web program. How this makes it more understandable.
- MP3 format, Module development, what they want to put this data, also cross-references.
- design issues behind the code.
- paradox of open system.

-Used a lot of Bioinformatics tools with a very little or no documentation.
Has to

