---
title: "Literate Programming..."
author: "Ben Buzzee"
topic: "08"
layout: post
root: ../../../
---


### Reproducible Reserch

In the 1995 paper by Donoho, I thought the following quote succinctly summarized
the key idea:

> An article about computational science in a scientific publication is not the
> scholarship itself, it is merely advertising of the scholarship. The actual scholarship
> is the complete software development environment and the complete set
> of instructions which generated the figures.


This quote strikes at the very heart of science. Without reproducibility, the validity of 
scientific publications becomes an issue of faith. Humans are erroneous creatures, and 
a consensus is far more valuable than any one particular result.

I also found myself relating to Donoho's lack of self trust:

>Roughly speaking, he didn’t trust himself to do good work unless his results were
>subject to open criticism by others.

As I currently work through a data analysis project, I can't help but think an error might slip
through despite my best efforts. After spending a substantial amount of time staring and thinking
about the same code, I wonder if a set of fresh eyes and a different perspective would reveal
details or mistakes I had not noticed. In this sense I am skeptical of myself and would appreciate
any attempts to reproduce the same results. Particularly when an important scientific conclusion is on
the line, I don't see how a result can be validated if the research is not reproducible.
