---
title: "Reproducible Research"
author: "Matt Stuart"
topic: "08"
layout: post
root: ../../../
---

## Constrasts and Comparisons of the Reproducibility Papers

Obviously, both papers discuss the issue of reproducibility of research, and they both discuss the *WaveLab* package that was produced to be able to reproduce the research on wavelets, along with other methods of reproducibility such as *SparseLab* and *SymmLab* in the second paper.  The themes of issues involving reproducibility are common in both papers, since the first paper discusses the issues in their line of reproducing data and the second goes into why some researchers would be weary of making research that are reproducible.

Because the first paper was written in the 1990s and the internet was not fully available as it is today, that paper is more focused on the future of reproducibility of research, why it is so important, and how it can be implemented using a variety of methods such as the internet.  Specifically, it went into the topic of problems in their own line of work, explaining why those issues led to the invention of *WaveLab*. This is why the introduction of *WaveLab* was so important to this first paper, since it was one of the first such computer programs to allow other researchers to conduct their own experiments.  The other important takeaway from this paper was the discussion on the internet as well.  As earlier pointed out, the internet was growing at a rapid pace at that time, so methods to reproduce research can be easily and efficiently given to each other.

The second paper *15 Years of Reproducible Research* dives more into this topic, while discussing how the introduction of *WaveLab* has been a sort of benchmark, since it had been cited 690 times since its inception until 2007 for other's research.  
